version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: webshop
    ports:
      - "5432:5432"
    networks:
      - webshop

  smtp4dev:
    image: rnwood/smtp4dev:latest
    container_name: smtp4dev
    ports:
      - "25:25"     # SMTP port
      - "8080:80"   # Web UI port
    environment:
      - "SMTP_USERNAME=testuser"
      - "SMTP_PASSWORD=testpass"
    volumes:
      - smtp-data:/smtp-data   # To persist data
    restart: always

volumes:
  smtp-data:
    driver: local

networks:
  webshop:
    name: webshop
    driver: bridge