version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: webshop
    ports:
      - "5432:5432"
    networks:
      - webshop

networks:
  webshop:
    name: webshop
    driver: bridge