name: Build, Test, and Deploy ASP.NET Core API

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

env:
  DOTNET_VERSION: '9.0'

jobs:
  build_api:
    runs-on: ubuntu-latest

    env:
      PROJECT_PATH: './Src/V1'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check directory
        run: ls -la

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies for API
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build API project
        run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release

      - name: Run tests for API project
        run: dotnet test ${{ env.PROJECT_PATH }} --configuration Release

  build_tests:
    runs-on: ubuntu-latest
    needs: build_api

    env:
      TEST_PROJECT_PATH: './tests/V1.Tests'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies for tests
        run: dotnet restore ${{ env.TEST_PROJECT_PATH }}

      - name: Build tests project
        run: dotnet build ${{ env.TEST_PROJECT_PATH }} --configuration Release

      - name: Run tests
        run: dotnet test ${{ env.TEST_PROJECT_PATH }} --configuration Release
