name: Build, Test, and Deploy ASP.NET Core API

on:
  push:
    branches:
      - dev

env:
  DOTNET_VERSION: '9.0'

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      PROJECT_PATH: './src/V1'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies for API
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build API project
        run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ${{ env.PROJECT_PATH }}/bin/Release/net9.0

  test:
    runs-on: ubuntu-22.04
    needs: build

    env:
      TEST_PROJECT_PATH: './tests/V1.Tests'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies for tests
        run: dotnet restore ${{ env.TEST_PROJECT_PATH }}

      - name: Build tests project
        run: dotnet build ${{ env.TEST_PROJECT_PATH }} --configuration Release

      - name: Run tests
        run: dotnet test ${{ env.TEST_PROJECT_PATH }} --configuration Release
